### ISSUE TITLE
parsing of addresses with "," will result in wrong coordinates

### ISSUE THREAD

**Issue by woodii** [k3b/k3b-geoHelper#7]
Parsing of some address strings will result in lat, lng getting populated with housnumbers or zips.

Thomas-Klestil-Platz 13, 1030 Wien, Austria
geo:0,0?q=Thomas-Klestil-Platz%2013%2C%201030%20Wien%2C%20Austria

lat = 13
lng = 1030

![image](https://user-images.githubusercontent.com/1383203/147074085-bade7ad2-fe04-48ba-a1ab-8806244786db.png)

Thats exactly how the google contacts app passes saved address to apps supporting geo intents.
When using linebreaks instead of "," everything works fine.

Thomas-Klestil-Platz 13
1030 Wien
Austria
geo:0,0?q=Thomas-Klestil-Platz%2013%0A1030%20Wien%0AAustria
lat = 0.0
lng = 0.0

**Comment by woodii** [comment]
from a first look it should be possible to add ^ before the regex used to parse the 2nd data part.
^([+\-nNeEsSwW]?[0-9\.]+)(?:\s*,\s*([+\-nNeEsSwW]?[0-9\.]+))(?:\s*,\s*([+\-nNeEsSwW]?[0-9\.]+))?

**Comment by k3b** [comment]
@woodii thanks for reporting.

I did 2 fixes:

* lat/long is only set if both are between -180 and +180
* unless "inferMissing" is enabled: lat/lon is only set if there is no " " before lat.

Additional test cases:

* geo:0,0?q=Testgasse13, 12345 Testhausen, Germany => no lat lon because "12345" is > 180
* geo:0,0?q=Testgasse 13, 00045 Testhausen, Germany => no lat lon because there is a " " befor the 13

When "inferMissing" is enabled "geo:0,0?q=Testgasse 13, 00045 Testhausen, Germany" => (13,45)
